version: "3.9"

services:
  book-service:
    build: ./book-service
    ports:
      - "8001:8000"
    depends_on:
      - db

  auth-service:
    build: ./auth-service
    ports:
      - "8002:8000"
    depends_on:
      - db

  notification-service:
    build: ./notification-service

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: