FROM python:3.11-slim

WORKDIR /app

COPY api_gateway/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY common /app/common
COPY api_gateway/ /app/api_gateway/

ENV PYTHONPATH=/app:/app/api_gateway

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]